@baseUrl = http://localhost:5000/api/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2NjQ3MTU3NiwianRpIjoiMjVhZTA1ODktMGUxMC00MWMyLWJmZGItNTU0YTIwYWJmNDU4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY5NGEzNjk2ZTYzNzk4OTk2ZDE3ZWRlNSIsIm5iZiI6MTc2NjQ3MTU3NiwiY3NyZiI6IjQxYWRkZmNlLTkxZTAtNDcwMC04MGVmLWM4ZDdmNmU4ZTM5YSIsImV4cCI6MTc2NjQ3MjQ3Nn0.9Ubl5q-MmVXOFWCcZY1D4izZt83HIMns9rYLSOkJgM0

### Create User (POST)
POST {{baseUrl}}/user/signup
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "username",
  "email": "john@example.com",
  "password": "secret123"
}

### Create User (POST)
POST {{baseUrl}}/user/login
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "john@example.com",
  "password": "secret123"
}

### verify mail
GET {{baseUrl}}/mail/verify/694a4035e8148906958d98b2/aea6dc7e-6955-4f63-911d-23e59984b7a5